增加多次尝试拉取代码

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,8 +20,28 @@ jobs:
         key: ${{ secrets.SERVER_SSH_KEY }}
         script: |
           cd /root/birdhelper
-          git pull
-          docker build -t slack-bot .
+
+          # 设置最大尝试次数和重试延时
+          MAX_RETRIES=10
+          RETRY_DELAY=1
+
+          # 执行git pull，直到成功或达到最大尝试次数
+          attempt=1
+          while [ $attempt -le $MAX_RETRIES ]
+          do
+              git pull && break
+              echo "Attempt $attempt failed! Trying again in $RETRY_DELAY seconds..."
+              attempt=$((attempt+1))
+              sleep $RETRY_DELAY
+          done
+
+          if [ $attempt -gt $MAX_RETRIES ]; then
+              echo "Failed to git pull after $MAX_RETRIES attempts."
+              exit 1
+          fi
+
+          # 继续执行后续命令
+          docker build -t slack-bot . --no-cache
           docker stop slack-bot || true
           docker rm slack-bot || true
           docker run -d --name slack-bot -p 5000:5000 slack-bot
